#!/bin/sh
#
#   Launch the XMonad window manager.
#   Before to launch it, ensures that "xmonad --recompile" has been called
#   since the last update of binary, libraries or configuration files
#


# First step: locate the xmonad user configuration file.
# If it does not exist, impossible to launch xmde. Print an error and exit.
# If it exists, get its modification date.
#
if [ ! -d "$HOME/.xmonad" -o ! -f "$HOME/.xmonad/xmonad.hs" ] ; then
    echo "xmde: missing xmonad configuration file '$HOME/.xmonad/xmonad.hs'"
    echo "Please visit 'https://wiki.haskell.org/Xmonad/Config_archive'"
    exit 1
else
    conftime=$(stat -c '%Z' "$HOME/.xmonad/xmonad.hs")
fi>&2


# Second step: locate the xmonad user executable.
# If this executable does not exist, then recompile. Otherwise, get the
# modification date.
#
for file in "$HOME/.xmonad/xmonad-"* ; do
    if [ -f "$file" -a -x "$file" ] ; then
	found="$file"
	break
    fi
done

if [ "x$found" = 'x' ] ; then
    if ! xmonad --recompile ; then
	echo "xmde: cannot recompile xmonad"
	exit 1
    fi >&2
fi

exectime=$(stat -c '%Z' "$found")


# Third step: compare the executable time and the configuration file time.
# If the configuration file is newer than the executable, then recompile
#
if [ $conftime -gt $exectime ] ; then
    if ! xmonad --recompile ; then
	echo "xmde: cannot recompile xmonad"
	exit 1
    fi >&2

    exectime=$(stat -c '%Z' "$found")
fi


# Fourth step: compare to the package files.
# If the executable is older than any file listed in the packages 'xmonad' or
# 'xmonad-contrib', then recompile.
#
pacman -Ql 'xmonad' 'xmonad-contrib' | cut -d' ' -f 2 | while read file ; do
    pkgtime=$(stat -c '%Z' "$file")

    if [ $pkgtime -gt $exectime ] ; then
	if ! xmonad --recompile ; then
	    echo "xmde: cannot recompile xmonad"
	    exit 1
	fi >&2

	break
    fi
done

exectime=$(stat -c '%Z' "$found")


# Fifth step: launch xmonad
# If the --restart option is specified, then only restart xmonad instead of
# launching it.
#
if [ "x$1" = 'x--restart' ] ; then
    exec xmonad --restart
else
    exec xmonad
fi
