#!/bin/sh

set -e


get_volume() {
    amixer sget Master \
	| tail -n 1 \
	| sed -r 's/^.*\[([[:digit:]]+)%\].*$/\1/'
}

is_mute() {
    amixer sget Master | tail -n 1 | sed -r 's/^.*\[(on|off)\].*$/\1/'
}


show_volume() {
    local mutemx=$(is_mute)

    if [ "$mutemx" = "on" ] ; then
	get_volume
    else
	echo 0
    fi
}

set_up() {
    local volume=$(get_volume)

    volume=$(( $volume + 10 ))
    if [ $volume -gt 100 ] ; then
	volume=100
    fi

    amixer sset Master unmute   > /dev/null
    amixer sset Master $volume% > /dev/null
}

set_down() {
    local volume=$(get_volume)

    volume=$(( $volume - 10 ))
    if [ $volume -lt 0 ] ; then
	volume=0
    fi

    amixer sset Master unmute   > /dev/null
    amixer sset Master $volume% > /dev/null
}

set_mute() {
    amixer sset Master toggle   > /dev/null
}


if [ $# -eq 1 ] ; then
    command="$1" ; shift
elif [ $# -eq 0 ] ; then
    command="show"
else
    exit 1
fi


case "$command" in
    up)
	set_up
	show_volume
	;;
    down)
	set_down
	show_volume
	;;
    mute)
	set_mute
	show_volume
	;;
    show)
	show_volume
	;;
    *)
	exit 1
esac


exit 0
